# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf0d4f679a368126ad09aa5b4181bc91f8fe9c0e344a050c94de6fc77ed8bc457cf6255347aaf6bc7fccd5f2ef1acc20761fa84b339112bb2474d63cd2784f78

test:
  secret_key_base: d27e0ee8fe221e0f45afc45a57c1dc890a856dc3dca0bfd41271ea090aa52cb7f34952670831a3918d5123127fff727962e683b4c91a3acb2201c0ef3b0743e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
